# ~/.config/kitty/kitty.conf
font_family        JetBrainsMono Nerd Font
font_size          11.0
background_opacity 0.95
foreground #acacac
window_padding_width 5
scrollbar_width 0
map ctrl+l clear_terminal scrollback active
scrollback_lines 1000
scrollback_pager_history_size 10
cursor_blink_interval 0
