#!/bin/env bash
echo "Installing Dependencies..."
sudo pacman -S waybar swaybg wf-recorder wl-clipboard slurp grim ttf-jetbrains-mono-nerd noto-fonts-cjk noto-fonts-emoji zip unzip pavucontrol --noconfirm
echo "checking directories..."
mkdir -p ~/.config
mkdir -p /home/$USER/Pictures/Screenshots
mkdir -p /home/$USER/Videos/records
echo "copying wofi configurations..."
cp -r wofi ~/.config
echo "installing dunst configurations..."
cp -r dunst ~/.config
echo "installing hyprland configurations..."
cp -r hypr ~/.config
echo "installing waybar configurations..."
cp -r waybar ~/.config
echo "installing kitty configurations..."
cp -r kitty ~/.config
echo "installing cursor configurations..."
cp -r cursor ~/.local/share/icons
echo "refreshing fonts"
fc-cache -fv
echo "installing wallpapers..."
cp -r wallpaper /home/$USER/Pictures/
echo "Setup completed. Restart your hyprland (SUPER + M) to make changes of  wallpapers & fonts. "

